services:
  cms:
    image: ghcr.io/ntuscse/website/cms
    ports:
      - 80:3000
    env_file:
      - cms.env
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - ./data:/data/db
    # logging:
    #  driver: none
    restart: always

volumes:
  data:
