services:
  cms:
#    image: ghcr.io/ntuscse/website/cms
    build:
      context: ../../
      dockerfile: ./apps/cms/docker/staging/Dockerfile
    networks:
      - cms-network
#    ports:
#      - "80:80"
    env_file:
      - cms.env
    restart: always
    depends_on:
      - mongo
    labels:
      - "traefik.http.routers.cms.rule=Host(`localhost`)"

  mongo:
    image: mongo:latest
    networks:
      - cms-network
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - ./data:/data/db
    restart: always

  traefik:
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cms-network

#  nginx:
#    image: ghcr.io/ntuscse/website/nginx-staging
##    build: ./nginx
#    networks:
#      - cms-network
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - cms

networks:
  cms-network:
    driver: bridge

volumes:
  data:
