---
services:
  traefik:
    container_name: traefik
    image: traefik:v2.9
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      #- "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@ntuscse.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      default:
      cms_network:
        ipv4_address: 10.5.0.99
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.traefik.rule=Host(`traefik.staging.ntuscse.com`)"
      #- "traefik.http.routers.traefik.entrypoints=web"

  cms:
    container_name: cms
    image: ghcr.io/ntuscse/website/cms:latest
    networks:
      cms_network:
        ipv4_address: 10.5.0.2
    env_file:
      - cms.env
    restart: always
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms.rule=Host(`$TRAEFIK_HTTP_CMS_HOST`)"
      - "traefik.http.routers.cms.entrypoints=websecure"
      - "traefik.http.routers.cms.tls.certresolver=myresolver"
  mongo:
    container_name: mongo
    image: mongo:latest
    networks:
      cms_network:
        ipv4_address: 10.5.0.3
    volumes:
      - ./db_data:/data/db
    restart: always

  merch:
    container_name: merch
    image: ghcr.io/ntuscse/website/merch:latest
    networks:
      cms_network:
        ipv4_address: 10.5.0.4
    env_file:
      - merch.env
    restart: always
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.merch.rule=Host(`$TRAEFIK_HTTP_MERCH_HOST`)"
      - "traefik.http.routers.merch.entrypoints=websecure"
      - "traefik.http.routers.merch.tls.certresolver=myresolver"

  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./data/uptime-kuma:/app/data"
    restart: always
    networks:
      - default
    logging:
      options:
        max-size: 1g
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`$TRAEFIK_HTTP_UPTIME_KUMA_HOST`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=myresolver"
      # - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
  
  challenges:
    container_name: challenges
    image: ghcr.io/ntuscse/website/challenges:latest
    networks:
      cms_network:
        ipv4_address: 10.5.0.5
    env_file:
      - challenges.env
    depends_on:
      - mongo
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.merch.rule=Host(`$TRAEFIK_HTTP_CHALLENGES_HOST`)"
      - "traefik.http.routers.merch.entrypoints=websecure"
      - "traefik.http.routers.merch.tls.certresolver=myresolver"

networks:
  default:
    driver: bridge
  cms_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
