name: CD Staging

on:
  push:
    branches: [ main ]
  pull_request: # TODO: remove this before merging
    types: [opened, synchronize] # TODO: remove this before merging
  workflow_dispatch:

jobs:
  build-cms:
    name: Build CMS Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./apps/cms/docker/staging/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/website/cms:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/website/cms:latest

  deploy-to-staging:
    name: Deploy To Staging
    runs-on: ubuntu-22.04
    needs:
      - build-cms
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy and run docker images
        env:
          PRIVATE_KEY: ${{ secrets.STAGING_EC2_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.STAGING_EC2_HOSTNAME  }}
          USER_NAME: ${{ secrets.STAGING_EC2_USERNAME  }}
        run: |
          pwd
          ls
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key ./deployments/staging/docker-compose.yml ${USER_NAME}@${HOSTNAME}:/home/ubuntu/deployment
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/deployment &&
            docker compose pull &&
            docker compose up -d
          '
