name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Lint, Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }} # remote caching
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }} # remote caching
      WORDPRESS_API_URL: ${{ secrets.WORDPRESS_API_URL }} # for web

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Run Prettier
        id: prettier-run
        uses: rutajdash/prettier-cli-action@v1.0.0
        with:
          config_path: ./.prettierrc

      # This step only runs if prettier finds errors causing the previous step to fail
      # This steps lists the files where errors were found
      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "❌ The following files are not formatted:"
          echo "${{steps.prettier-run.outputs.prettier_output}}"
          echo "⭐️ You should run `yarn format` in the root of the project directory to fix these files"

      - name: Lint + Build + Unit Test
        run: yarn turbo run lint build test cypress:start-headless --parallel
        env:
          WORDPRESS_API_URL: 'https://clubs.ntu.edu.sg/csec/graphql'
